language: cpp

matrix:
  include:
    #######################################################
    - os: linux
      dist: xenial
      name: cpplint (code style)
      install:
        - sudo apt-get install python3-pip
        - sudo pip install --upgrade pip
        - sudo pip install setuptools cpplint
      script:
        - python build.py lint
    #######################################################
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
        - sudo apt-get install libomp*
      script:
        - git submodule update --init --recursive
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build . --config Release -- -j2
        - ./bin/test_target
        - ./bin/benchmark_target
        - ./bin/example_pipelines ../samples/example_pipelines/pipeline.yaml
    #######################################################
    - os: linux
      dist: xenial
      compiler: clang
      install:
        - sudo apt-get install libiomp*
      script:
        - python build.py build clang
        - python build.py test clang parallel
        - python build.py benchmark clang
        - python build.py pipelines clang samples/example_pipelines/pipeline.yaml
    #######################################################
    - os: osx
      osx_image: xcode10.1
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install libomp
      script:
        - python build.py build clang
        - python build.py test clang parallel
        - python build.py benchmark clang
        - python build.py pipelines clang samples/example_pipelines/pipeline.yaml
    #######################################################
